- vanilla_first_setup/gtk/window.ui
I switched from "Light" to "Default" because GNOME names it that way since GNOME 42.
> Improve wording

- data/io.github.vanilla-os.FirstSetup.appdata.xml.in
I’m thinking that might be a leftover from a previous name of the project?
> Vanilla OS instead of “Ubuntu Vanilla GNOME”

- vanilla_first_setup/gtk/progress.ui
- vanilla_first_setup/gtk/window.ui
- vanilla_first_setup/window.py
make `progress_screen` and `done` pages have no carousel and title-buttons becuase:
- carousel in `progress_screen/tour` will confuse users that the carousel_indicators are for tour and not for pages
-  hide `titlebuttons` as it's not to close the window when changes are being applied
- also made progress-bar text as label (_same as vanilla installer_)
> Misc changes

- recipe.json
- as the vanilla meta package already does this, first-setup shouldn't override it again
> remove gs gsettings commands

- recipe.json
During setup i realized a dead end when following the "Read More" button in first-setup.
I know these are small changes i tried this as my first contribution including a pull request to an open source project ever.
So i'd be over the moon seeing it merged into upstream. ;-D
Cheers
> fixed hyperlink directing to ABRoot documentation

- vanilla_first_setup/utils/processor.py
Using the stock `recipe.json`, I encountered some syntax errors around the conn-check in the `NamedTemporaryFile` in `utils/processor.py`;
```bash
wget -q --spider cloudflare.comif [ $? != 0 ]; thenecho 'No internet connection!'exit 1export DEBIAN_FRONTEND=noninteractive
```
where it should look like:
```bash
wget -q --spider cloudflare.com
if [ $? != 0 ]; then
echo 'No internet connection!'
exit 1
fi
export DEBIAN_FRONTEND=noninteractive
[...]
```
> fix: Change conn-check syntax

- vanilla_first_setup/main.py
Fixes first-setup failing to start due to `CssProvider().load_from_data()` getting too many arguments
> Fix css-provider getting too many arguments

- data/firstsetup.desktop
- data/meson.build
Adds the X-GDM-SessionRegisters property to the session desktop file and installs it to both xsessions and wayland-sessions.
Closes #206
> Fix the first setup custom session

- first_setup_post_boot
Changes the session in the accountsservice file for the user running first-setup to gnome, ensuring that the user does not log into the first setup session again
Requires change in vanilla-installer/albius, ~~PR to be done~~ change added in https://github.com/Vanilla-OS/vanilla-installer/commit/7bc03be840d5d4c626ff2490641cd6fead2a105b
Unlocks https://github.com/Vanilla-OS/desktop-image/pull/12
Closes #197 upon merging this and related pull requests
> Change accountsservice file on finish

- data/firstsetup.desktop
Adds the NoDisplay property to the custom first setup session, so that it is hidden from the user but can still be set as the default and used by AccountsService
> Hide Custom Session in GDM

- vanilla_first_setup/defaults/network.py
This commit fixes a crash that happens when refreshing wifi networks on the network page by calling the UI refresh code inside the main thread.
> fix: [close #223] Make wifi refresh thread-safe

- __first_setup_reset_session
Resets the default session of a user to gnome once first-setup completes this stops users from being trapped in an endless loop of always logging into the restricted first-setup session
> fix: Reset user session once first-setup completes

- __first_setup_reset_session
- recipe.json
The login session is set in `/var/lib/AccountsService/users/$REAL_USER`. This fails because the bash script is interpreted by dash, not bash. That also means that the AccountsService file for the vanilla user is set but not the one for $REAL_USER.
Setting the -c flag runs the bash script as a command instead and works as expected.
Secondly, the flag -e for echo is missing in the first part of the script. This means that \n is not interpreted as a newline but instead just written to the file. (The file for the $REAL_USER is written correctly using the -e flag)
After a reboot, gdm (I think) detects that the file `/var/lib/AccountsService/users/vanilla` is formatted incorrectly and would delete both configurations, also the correct one. (for some reason)
This causes gdm to show no user …
> fix:[#228] first setup looping and not selecting gnome as the login environment

- vanilla_first_setup/defaults/user.py
- vanilla_first_setup/gtk/default-user.ui
The way that passwords are handled currently is insecure, see:
Fixes #276 
Fixes #284 
The password should never be written on disk in plaintext.
Implementing it in a safe and robust manner would probably require a completely different architecture. 
For this reason, it is probably better to hand this responsibility to the display manager. If a password is expired, the display manager will ask for a new password, removing the need for setting it through first setup.
> fix [#276 #284]: removes handling of password

- vanilla_first_setup/utils/processor.py
Setting the theme doesn't work if gsettings can't access the dbus. 
This uses systemd-run instead of su, to create a user environment with dbus. 
Fixes #269
> fix [#269]: runs user commands with dbus access

- data/org.vanillaos.FirstSetup.desktop.in
- vanilla_first_setup/utils/processor.py
Since the first setup is always started automatically, the desktop file should always be hidden in the menu.
Fixes #287
> fix [#287]: removes unnecessary desktop file

- vanilla_first_setup/utils/processor.py
The first-setup might fail without internet access so we need to wait until internet access is available.
Fixes #274
> fix [#274]: waits for internet connection after second boot

- vanilla_first_setup/main.py
This disables the lock screen for the default user to prevent locking the user out on inactivity or when pressing Ctrl+L accidentally. 
Fixes #289
> fix [289]: removes lock screen for default user

- recipe.json
Fixes #317
Seems like GNOME Web needed to be updated in a couple places in the recipe in 9c0b2fb
> Fix gnome web in recipe

- __first_setup_reset_session
- vanilla_first_setup/main.py
- vanilla_first_setup/utils/builder.py
- vanilla_first_setup/utils/processor.py
- vanilla_first_setup/vanilla-first-setup-prepare-files.in
- vanilla_first_setup/window.py
Tested on a VM, worth at least another test from someone else.
> fix[close #320]: Newly created users are required to create a new user

- __first_setup_reset_session
- vanilla_first_setup/defaults/user.py
- vanilla_first_setup/main.py
- vanilla_first_setup/utils/processor.py
The new-user mode is actually never called from anywhere. 
This determines the mode from the currently logged in user.
The vanilla user can't be used anyway with the current approach so this workaround won't cause any more problems.
Since  #222 is planned this is a valid workaround in my opinion.
Tested both with a fresh install and with a new user afterwards.
> fixes new-user mode

- recipe.example.json
- recipe.json
- vanilla_first_setup/gtk/done.ui
- vanilla_first_setup/views/done.py
- vanilla_first_setup/window.py
- default no-prompt logout
- add reboot_condition to recipe
- add set_reboot function that sets message and buttons
closes #323
> Feat: Reboot only when needed

- debian/control
Network manager is required for getting device and interface information.  It should be added as a dependency.
> fix: add network-manager dependency

- vanilla_first_setup/defaults/conn_check.py
- vanilla_first_setup/defaults/network.py
- vanilla_first_setup/utils/meson.build
- vanilla_first_setup/utils/network.py
- Split out network check from conn_check into static function
- Check for network by request success instead of network interfaces
Closes #339
> fix:[#339] network check without network interface

- README.md
- debian/control
- vanilla_first_setup/core/languages.py
- vanilla_first_setup/core/timezones.py
- vanilla_first_setup/defaults/keyboard.py
- vanilla_first_setup/defaults/network.py
- vanilla_first_setup/main.py
- add dependency info to readme
- add dependency info to debian/control
- move requires to source files instead of main
closes #350 
closes #351 
closes #352 
closes #353 
closes #354 
I can split this up if it is preferred
> fix: update dependency information

- vanilla_first_setup/gtk/done.ui
- vanilla_first_setup/gtk/post-script.ui
- vanilla_first_setup/views/done.py
- vanilla_first_setup/views/post_script.py
I reworked the retry button to go back to view logs.  its really annoying when theres an issue and it auto moves to done without letting the user see whats up.  the logging doesnt even work at the moment so its a bear to try to figure out whats wrong with the post scripts.  i plan to address the logging portion of that in another PR.  Also, the retry button doesnt rerun the script so its more or less the same functionality.
- convert retry button to view logs
- add next button to post script view
- increase margin for terminal box
> feat: view logs after post script run

- recipe.example.json
- recipe.json
- vanilla_first_setup/views/done.py
- add recipe keys for reboot and close commands
- call custom commands with subprocess instead hardcoded commands
- add recipe keys to example
closes #358
> feat:[#358] add custom reboot and close commands

- vanilla_first_setup/views/hostname.py
Update the regex to allow for digits in the hostname validation.
closes #377
> fix:[#377] allow digits in hostname

- vanilla_first_setup/views/hostname.py
See this discussion for reference:
[Multiple labels in the hostname are not recommended.](https://github.com/Vanilla-OS/first-setup/pull/380#discussion_r1985796602)
> removes multiple labels from verification
