- recipe.json
Tiny language flow changes as well as fixing a [double negative](https://en.wikipedia.org/wiki/Double_negative#Two_negatives_resolving_to_a_positive).
> Fixing language flow and a double negative

- README.md
fix(docs): Fix type in `README.md`
Replace: It's *(it is)* purpose is to help
By: Its purpose is to help
> fix(docs): Fix type in `README.md`

- vanilla_first_setup/gtk/done.ui
Since this might end up being used on other devices including Macs and tablets and phones, maybe having something less specific and technical than “PC” could be interesting?
> Change PC to Device?

- vanilla_first_setup/views/done.py
> PC to Device

- recipe.json
- perhaps the wording around the strings could be better, open to the suggestions.
> detect if in virtual env and prompt to install open-vm-tools

- recipe.json
Have ran through the first setup quite a few times now and noticed a minor English mistake. My first ever pull request, hopefully I did this right!
> Minor wording improvements

- recipe.json
Signed-off-by: K.B.Dharun Krishna <kbdharunkrishna@gmail.com>
> Update Package manager descriptions to generic ones

- vanilla_first_setup/defaults/conn_check.py
This fixes the network check to work more reliably
> Fix network check

- recipe.json
- vanilla_first_setup/defaults/applications.py
- vanilla_first_setup/defaults/meson.build
- vanilla_first_setup/defaults/user.py
- vanilla_first_setup/gtk/default-user.ui
- vanilla_first_setup/gtk/window.ui
- vanilla_first_setup/meson.build
- vanilla_first_setup/utils/builder.py
- vanilla_first_setup/utils/parser.py
- vanilla_first_setup/utils/processor.py
- vanilla_first_setup/vanilla-first-setup.gresource.xml
- vanilla_first_setup/views/progress.py
- vanilla_first_setup/window.py
This PR adds user creation to first-setup.
We still need to decide what to do with the dummy user we'll create during the installation process
> User creation

- vanilla_first_setup/defaults/conn_check.py
This PR updates the host used to check the internet connection.
> Updates connection check host (Closes #171)

- README.md
- po/POTFILES
- po/vanilla-first-setup.pot
- vanilla_first_setup/gtk/default-hostname.ui
- vanilla_first_setup/gtk/default-network.ui
- vanilla_first_setup/gtk/default-user.ui
- vanilla_first_setup/gtk/default-welcome.ui
- vanilla_first_setup/gtk/wireless-row.ui
- Fix translation strings in UI files.
- Add file entries to POTFILES.
- Update strings in the POT file.
- Fix Markdown heading spacing in README.
> cleanup: update translations

- vanilla_first_setup/defaults/network.py
Same fix applied to [vanilla-installer](https://github.com/Vanilla-OS/vanilla-installer/pull/266/files).
Closes #216
> Fix: Network page crash

- recipe.json
> fix: [close #243] Add Flathub repo

- recipe.json
Depends on https://github.com/Vanilla-OS/desktop-image/pull/121
> feat: enable apx-vso-pico Systemd service

- vanilla_first_setup/defaults/timezone.py
> feat:[#297] Make timezone search require at least 2 chars to filter

- vanilla_first_setup/defaults/welcome.py
> feat:[#296] Disable advanced button if there are no advanced options

- recipe.json
> fix[#305]: all browsers are installed by default

- vanilla_first_setup/defaults/user.py
> feat[#271]: Automatically generate a username based upon the full name.

- vanilla_first_setup/defaults/keyboard.py
- Add callback function for radio button and row to use for selection
closes #336
> Fix: toggle not selecting keyboard

- vanilla_first_setup/utils/processor.py
Move connection check to use flathub.org
Closes #275
> fix:[#275] move conn check to flathub from cloudflare

- vanilla_first_setup/core/languages.py
- Translate using locale if available
closes #329
> fix:[#329] Don't translate languages

- debian/vanilla-first-setup.install
- first-setup.txt
- recipe.json
- vanilla_first_setup/defaults/conn_check.py
- vanilla_first_setup/main.py
- vanilla_first_setup/utils/builder.py
- vanilla_first_setup/utils/recipe.py
- vanilla_first_setup/window.py
- move log config to main init
- log_file path to /tmp
- remove logging config from conn_check
- set logging level to debug
- set log file permissions
closes #348
> Fix: [#348] log output to writable directory

- recipe.json
> fix [#364]: use correct session after logout

- README.md
minor README fix for readability
> fix: wrap CLI args in code formatting

- vanilla_first_setup/apps.json
> close [#372 #374]: Feat/add apps

- README.md
> fix [#384]: adds information about custom images to README
